export const STEP_OF_ANALYSIS = {
  INITITAL: 0,
  ERROR: 1,
  FINISHED: 2,
  UNKNOWN_PROFILE: 3,
  PROFILE: 4,
  POSTURLS: 5,
  ALBUMS: 6,
  TRACKS: 7,
  VIDEO_COMMENTS: 8,
  SEGMENTS: 9,
  CREATING_ARTIST: 10,
  SAVING_ANALYSIS: 11,
};
